nimbus.host: "las-goal-storm.oscar.priv"

#Topology
topology.workers: 5
topology.max.spout.pending: 20
topology.message.timeout.secs: 120

#Elasticsearch
elasticsearch.cluster.name: "elasticsearch"
elasticsearch.host.name: "las-goal-storm.oscar.priv"
elasticsearch.host.port: 9300

#Kafka URL Consumer
kafka.topic.crawl.name: "urlevent"
kafka.consumer.host.name: "las-goal-web.oscar.priv"
kafka.consumer.host.port: 2181

#Kafka URL Producer
kafka.producer.host.name: "las-goal-web.oscar.priv"
kafka.producer.host.port: 9092

#Redis
redis.host.name: "las-goal-search.oscar.priv"
redis.host.port: 6379

#Bloom Filter
bloomfilter.name: "Crawler_URL_BloomFilter"
bloomfilter.expected.count: 1000000
bloomfilter.falsePositive: 0.01

#Crawler
crawl.depth: 3

#Crawler Web Server
web.server.port: 9080